[versions]
#Kotlin
kotlin = "1.6.10"
coroutines = "1.6.0"

#Multiplatform
napier = "1.4.1"
kotlinJson = "1.3.2"
kodein = "7.10.0"
ktor = "2.0.0"

#Android
accompanist = "0.24.6-alpha"
androidxhilt = "1.0.0"
androidxlifecycle = "2.5.0-alpha03"
compose = "1.2.0-alpha07"
composesnapshot = "-" # a single character = no snapshot
material3 = "1.0.0-alpha09"
paging = "3.1.0-rc01"
room = "2.4.0-alpha05"
coil = "1.4.0"

#Android Tests
androidxtest = "1.4.0"

[libraries]

#Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinJson" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

#Multiplatform
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kodein = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
#ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

#Accompanist
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerindicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-navigationanimation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigationmaterial = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }

#AndroidX
androidx-activity-compose = "androidx.activity:activity-compose:1.5.0-alpha03"
androidx-archCoreTesting = "androidx.arch.core:core-testing:2.1.0"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-collection = "androidx.collection:collection-ktx:1.2.0"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.0"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.0-alpha02"
androidx-datastore = "androidx.datastore:datastore-preferences:1.0.0"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.0-alpha06"
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha14"
androidx-palette = "androidx.palette:palette:1.0.0"
androidx-work-runtime = "androidx.work:work-runtime-ktx:2.8.0-alpha02"

#Room
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

#Android tests
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxtest" }
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.3"
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }
robolectric = "org.robolectric:robolectric:4.6.1"

#Android jetpack compose
compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }

#Coil
coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

#Google
google-analytics = "com.google.firebase:firebase-analytics-ktx:20.1.1"
google-crashlytics = "com.google.firebase:firebase-crashlytics-ktx:18.2.9"
google-crashlyticsGradle = "com.google.firebase:firebase-crashlytics-gradle:2.8.1"
google-gmsGoogleServices = "com.google.gms:google-services:4.3.10"

#Tests
junit = "junit:junit:4.13.2"
mockK = "io.mockk:mockk:1.12.2"

#Other
leakCanary = "com.squareup.leakcanary:leakcanary-android:2.8.1"
appauth = "net.openid:appauth:0.8.1"
threeTenAbp = "com.jakewharton.threetenabp:threetenabp:1.3.1"
truth = "com.google.truth:truth:1.1.3"