[versions]
napier = "2.6.1"
settings = "0.8.1"
kodein = "7.20.1"
ktor = "2.1.3"
sqlDelight = "1.5.5"
coil = "2.2.2"
voyager = "1.0.0-rc07"

[libraries]
gradle-mobile-multiplatform = "dev.icerock:mobile-multiplatform:0.14.1"
gradle-detekt = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.20.0-RC2"

multiplatform-logs = { module = "io.github.aakira:napier", version.ref = "napier" }
#multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }

#kodein
kodein = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kodein-jvm = { module = "org.kodein.di:kodein-di-generic-jvm", version.ref = "kodein" }
kodein-android-core = { module = "org.kodein.di:kodein-di-framework-android-core", version.ref = "kodein" }
kodein-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }
#ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
#SQLDelight
sqldelight-gradle = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }
sqldelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-driver-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-driver-native = { module = "com.squareup.sqldelight:native-drive", version.ref = "sqlDelight" }

#Coil
coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

#Google
google-analytics = "com.google.firebase:firebase-analytics-ktx:21.2.0"
google-crashlytics = "com.google.firebase:firebase-crashlytics-ktx:18.3.2"
google-crashlyticsGradle = "com.google.firebase:firebase-crashlytics-gradle:2.9.2"
google-gmsGoogleServices = "com.google.gms:google-services:4.3.14"
google-appDistribution = "com.google.firebase:firebase-appdistribution-gradle:3.1.1"
#Voyager
voyager-navigator = { module = "ca.gosyer:voyager-navigator", version.ref = "voyager" }
voyager-tab-navigator = { module = "ca.gosyer:voyager-tab-navigator", version.ref = "voyager" }
voyager-bottom-sheet-navigator = { module = "ca.gosyer:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-transitions = { module = "ca.gosyer:voyager-transitions", version.ref = "voyager" }
voyager-kodein = { module = "ca.gosyer:voyager-kodein", version.ref = "voyager" }

#Tests
junit = "junit:junit:4.13.2"
mockK = "io.mockk:mockk:1.12.2"

#Other
leakCanary = "com.squareup.leakcanary:leakcanary-android:2.8.1"
extendedGestures = "com.github.SmartToolFactory:Compose-Extended-Gestures:2.0.0"
uuid = "com.benasher44:uuid:0.7.0"

#//TODO remove with navigation refactoring
material-motion-navigation = "io.github.fornewid:material-motion-compose-navigation:0.10.3"
material-motion-core = "io.github.fornewid:material-motion-compose-core:0.10.3"

#for ktor logs
slf4j = "org.slf4j:slf4j-simple:1.7.30"

[bundles]
voyager = ["voyager-navigator", "voyager-tab-navigator", "voyager-transitions", "voyager-bottom-sheet-navigator", "voyager-kodein"]
